### PR TITLE
Fixes for the paper

### PR DESCRIPTION
**Pull request by pablooliveira**

### CODE REVIEW

**Comment by pablooliveira** [comment]
@gkiar, I'm currently rereading the paper in depth; sorry for the delay. I will use this PR to track any needed changes. Once I'm finished, I'll remove the WIP tag and you can merge what you think is useful.

In addition, I would recommend citing the following work, which I read last year and find quite pertinent and complementary to your paper,

Hupé, Jean-Michel. "Statistical inferences under the Null hypothesis: common mistakes and pitfalls in neuroimaging studies." Frontiers in neuroscience 9 (2015): 18. [Link](https://www.frontiersin.org/articles/10.3389/fnins.2015.00018/full)

**Comment by pablooliveira** [comment]
I really like and agree with the conclusion in lines 143-152; it's a very nice intuition ;-)

The discussion in page 6 and 7 is very well written and insightful !

**Comment by pablooliveira** [comment]
Very nice ! Thanks @gkiar.

**Review by gkiar — APPROVED** [review]
Thanks for the typos and Verificarlo addition to Code Availability, @pablooliveira ! As always, I appreciate your thorough reviews :)

**Pull request merged**
